name: run-tests
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        node-version: [20.x, latest, lts/*]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: pnpm-setup
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - run: pnpm install
      - run: pnpm run build
  pusblish-dry:
    name: Build & dry run on publish
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pnpm-setup
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org/
          scope: '@embodi'
          cache: 'pnpm'
      - name: Install
        run: pnpm install
      - name: Unit Test
        run: pnpm run test:ci
      - name: Build && publint
        env:
          #TODO: Change this later
          VITE_FORMURL: http://localhost:3011/f/random
        run: pnpm run prepublishOnly
      - name: Publish Dry Run
        run: pnpm -r publish --dry-run --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
