name: Playwright Tests
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
jobs:
  test:
    timeout-minutes: 60
    strategy:
      matrix:
        node-version: [20.x, latest, lts/*]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - name: pnpm-setup
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build Embodi
        env:
          #TODO: Change this later
          VITE_FORMURL: http://localhost:3011/f/random
        run: pnpm run build
      - name: Install Playwright Browsers
        run: pnpm run test:e2e:init
      - name: Run Playwright tests
        run: pnpm run test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
